package modele;
// Generated 5 mars 2014 00:03:03 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Lecteurcarte generated by hbm2java
 */
public class Lecteurcarte  implements java.io.Serializable 
{

	private static final long serialVersionUID = 1L;
	private int numlecteur;
     private Commercant commercant;
     private Set<Transactions> transactionses = new HashSet<Transactions>(0);

    public Lecteurcarte() {
    }

	
    public Lecteurcarte(int numlecteur) {
        this.numlecteur = numlecteur;
    }
    public Lecteurcarte(int numlecteur, Commercant commercant, Set<Transactions> transactionses) {
       this.numlecteur = numlecteur;
       this.commercant = commercant;
       this.transactionses = transactionses;
    }
   
    public int getNumlecteur() {
        return this.numlecteur;
    }
    
    public void setNumlecteur(int numlecteur) {
        this.numlecteur = numlecteur;
    }
    public Commercant getCommercant() {
        return this.commercant;
    }
    
    public void setCommercant(Commercant commercant) {
        this.commercant = commercant;
    }
    public Set<Transactions> getTransactionses() {
        return this.transactionses;
    }
    
    public void setTransactionses(Set<Transactions> transactionses) {
        this.transactionses = transactionses;
    }


	@Override
	public String toString() {
		return "Lecteurcarte [numlecteur=" + numlecteur + ", commercant="
				+ commercant.getNumcommercant() +",Raison Social:"+commercant.getRaisonSociale()+ ", transactionses=" + transactionses + "]";
	}




}


